= Metanorma Linux Setup

image:https://img.shields.io/travis/metanorma/metanorma-linux-setup/master.svg["Build Status", link="https://travis-ci.com/metanorma/metanorma-linux-setup"]
image:https://codeclimate.com/github/metanorma/metanorma-linux-setup/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/metanorma-linux-setup"]

== Purpose

This repository provides installation of the
https://github.com/metanorma/metanorma[Metanorma] publication toolchain
on Linux.


== Requirements

* https://www.ubuntu.com[Ubuntu (18.10 down to 12.04)]
* https://www.centos.org/[CentOS 7.x]

Older versions may work but are not tested.

== Install on Ubuntu

[source,sh]
----
# Prerequisites: "curl"
# apt-get update && apt-get install -y curl
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/install-gems.sh | bash
----

NOTE: The first command has to be run via `sudo`.


== Install on CentOS


[source,sh]
----
# Prerequisites: "curl"
# yum install -y curl
sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/centos.sh | bash"
curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/install-gems.sh | bash
----

NOTE: The first command has to be run via `sudo`.


== What it sets up

//* https://github.com/postmodern/chruby[chruby] for managing [Ruby] versions
* http://bundler.io[bundler] for managing [Ruby] gems
* https://java.com[Java] which is a dependency for some of the Metanorma gems
//* https://github.com/creationix/nvm[nvm] for managing http://nodejs.org[Node.js] versions (includes latest Node.js and https://www.npmjs.org[NPM], for running apps and installing JavaScript packages)
* http://nodejs.org[Node.js] (includes latest Node.js and https://www.npmjs.org[NPM], for running apps and installing JavaScript packages)
* https://github.com/GoogleChrome/puppeteer[puppeteer] for running Headless Chrome via Node.js (used to generate PDFs from HTML)
* http://plantuml.com/[PlantUML] for creating UML diagrams via plain-text


== Debugging

If you run into any problems, please copy and paste the entire log into a
https://github.com/metanorma/metanorma-macos-setup/issues/new[new GitHub Issue]
for us.

